pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

penguinpj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include("pages.urls")),
    path('students/', include('students.urls')),
    path('courses/', include('courses.urls') ),
    path('emaillists/', include('emaillists.urls') ),
    path('enrollments/', include('enrollments.urls')),
    path('forums/', include('forums.urls')),
    path('admin/', admin.site.urls),
]

students/urls.py
from django.urls import path
from . import views
app_name = 'students'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
]

templates/partials/_alert.html
{% if messages %}
    <!---if there is any messages then loop the messages object -->
    {% for message in messages %}
    <div id="message" class="container">
        <div 
            class="alert alert-{{ message.tags }}"
            role="alert"
            >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    Error:
                {% else %}
                    {{ message.tags|title }}
                {% endif %}
            </strong>
            {{ message }}
        </div>
    </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
<!-- Footer -->

<footer id="main-footer" class="py-6 bg-info text-white text-center">
    Copyright &copy;
    <span class="year"></span> A1 Open Source Ltd.
  </footer>

templates/partials/_navbar.html
<!-- Nav Bar -->
{%load static%}
<!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-info sticky-top">
      <div class="container">
        <a class="navbar-brand" href={% url 'pages:index' %}>
          <img src={% static "css/img/a1_logo.png" %} class="logo" alt="" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="navbar-nav">
            <li {% if '/' == request.path %}
                class="nav-item active mr-3"
            {% else %}
            class="nav-item mr-3"
            {% endif %}
            >
              <a class="nav-link" href={% url 'pages:index' %}>Home</a>
            </li>

            <li {% if 'about' in request.path %}
              <li class="nav-item active mr-3">
            {% else %}
              <li class="nav-item mr-3">
            {% endif %}
              <a class="nav-link" href={% url 'pages:about' %}>About</a>
            </li>
            
            
          </ul>

          <ul class="navbar-nav ml-auto">
          
          {% if user.is_authenticated %}
          <!-- dashboard link-->
          <li {% if 'dashboard' in request.path %} class='nav-item mr-3 active'
              {% else %} class='nav-item mr-3' {% endif %}>
              <a class="nav-link" href={% url 'students:dashboard' %} >Hi {{user.username}} Dashboard</a>
          </li>
          <!-- logout link-->
          <li class='nav-item mr-3'>
            <a href="javascript: {document.getElementById('logout').submit()}" class='nav-link'>
            <i class='fas fa-sign-out-alt'></i>Logout
            </a>
            <form action="{% url 'students:logout' %}" method="POST" id="logout">
            {% csrf_token %}
            <input type='hidden'>
            </form>
          </li>
          {% else %}
            <li {% if 'register' in request.path %}
              class="nav-item active mr-3"
              {% else %}
                class="nav-item mr-3" 
              {% endif %} >
              <a class="nav-link" href={% url "students:register" %}>
              <i class="fas fa-user-plus"></i> Register</a>
            </li>

            <li {% if 'login' in request.path %}
                    class="nav-item active mr-3"
                {% else %}
                    class="nav-item mr-3"
                {% endif %}>
              <a class="nav-link" href={% url "students:login" %}>
                <i class="fas fa-sign-in-alt"></i>
                Login</a>
            </li>
          {% endif %}
          </ul>
        </div>
      </div>
    </nav>

templates/partials/_topbar.html
<!-- Top Bar -->
<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="logo">A1</div>
            </div>
            
        </div>
    </div>
</div>