courses/urls.py
from django.urls import path
from . import views
from courses.models import Course

urlpatterns = [
    path('', views.index, name='courses'),
    path('<int:course_id>', views.listing, name='course'),
]

enrollments/urls.py
from django.urls import path
from . import views
app_name= 'enrollments'
urlpatterns = [
  #  path('', views.listing, name='listing'),
    path('<int:course_id>', views.enroll, name='enroll'),
]

pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

penguinpj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include("pages.urls")),
    path('students/', include('students.urls')),
    path('courses/', include('courses.urls') ),
    path('emaillists/', include('emaillists.urls') ),
    path('enrollments/', include('enrollments.urls')),
    path('forums/', include('forums.urls')),
    path('admin/', admin.site.urls),
]

courses/models.py
from django.db import models
from django.shortcuts import render
from datetime import datetime
from instructors.models import Instructor

# Create your models here.

class Course(models.Model):
 #   id = models.CharField(max_length=10)
    instructor_id = models.ForeignKey(Instructor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=30)
    catagory = models.CharField(max_length=20)
    keyword = models.CharField(max_length=50)
    price = models.IntegerField()
    prerequisite = models.CharField(max_length=10)
    deadline = models.DateField(default='', blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    current_enrollment = models.BigIntegerField(default=0)
    max_enrollment = models.BigIntegerField(default=0)
    location = models.CharField(max_length=15, blank=True)


    def __str__(self):
        return self.title

courses/views.py
from django.shortcuts import render
from django.contrib import messages
from courses.models import Course
from authuser.models import User
from enrollments.models import Enrollment
from students.models import Student
from datetime import timedelta
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone


# Create your views here.
def index(request):
    courses = Course.objects.order_by('id')
    context = {'courses': courses}
    return render(request, 'courses/listings.html', context )

def listing(request, course_id):
    #course = Course.objects.get(id=course_id)
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'courses/listing.html', {'course':course})

templates/courses/listing.html
{% extends 'base.html' %} 
{% load humanize %}
<!--add title to the tab-->
{% block title %} | Course Details {% endblock %}
{% block content %}
<div class="card-body">
    <ul class="list-group bg-secondary">Course selected       
       
            <div class="col-md-12">
                <p>Course Title: {{ course.title }}</p>
                <div class="p">Course category: {{ course.catagory }}</div>
                <div class="p">Course keyword: {{ course.keyword }}</div>
                <div class="p">Course price: ${{ course.price|intcomma }}</div>
                <div class="p">Course prerequisite: {{ course.prerequisite }}</div>
                <div class="p">Course registration deadline: {{ course.deadline }}</div>
                <div class="p">Course start date: {{ course.start_date }}</div>
                <div class="p">Course end date: {{ course.end_date }}</div>
                <div class="p">Course location: {{ course.location }}</div>
                <div class="p">Course capacity: {{ course.max_enrollment }}</div>
                {% if user.is_authenticated %}
                <div class="button">
                    <form action="{% url 'enrollments:enroll' course.id %}" method="POST">
                        {% csrf_token %}
                        <input
                            type="submit"
                            value="ENROLL"
                            class="btn btn-secondary btn-block"
                        />
                    </form>
                </div>
                {% endif %}
            </div>
    </ul>
</div>


{% endblock %}

templates/courses/listings.html
{% extends 'base.html' %} 
{% load humanize %}
<!--add title to the tab-->
{% block title %} | Course List {% endblock %}
{% block content %}
<section id="root">
    <div class="container mt-4">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-info">
                        <h4>Latest Courses</h4>
                        <h4>Latest Courses2</h4>

                    </div>
                    <div>
                    <h3 class="d-inline bg-success">Course Title</h3>
                    <h3 class="d-inline bg-success">Category</h3>
                    </div>
                
                    <div class="card-body">
                        <ul class="list-group bg-secondary>Course Title        Cat.       Start Date
                            {% if courses %}
                            {% for course in courses %}
                                <li class="list-group-item">
                                    <a href="{% url 'course' course.id %}">
                                         {{ course.title }}
                                         {{ course.catagory }}
                                         {{ course.start_date }}
                                    </a>
                                </li>
                            {% endfor %}
                            {% else %}
                                <div class="col-md-12">
                                    <p>No Listing Available</p>
                                </div>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>


{% endblock %}