forums/urls.py
from django.urls import path
from . import views

app_name = 'forums'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:forum_id>', views.forums, name='forums'),
    path('post', views.post, name='post'),
    path('add', views.add, name='add'),
]

pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

penguinpj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include("pages.urls")),
    path('students/', include('students.urls')),
    path('courses/', include('courses.urls') ),
    path('emaillists/', include('emaillists.urls') ),
    path('enrollments/', include('enrollments.urls')),
    path('forums/', include('forums.urls')),
    path('admin/', admin.site.urls),
]

forums/models.py
from django.db import models
from django.contrib.auth import get_user_model
#from .models import Course
# Get the custom User model
User = get_user_model()

# Create your models here.
class Forum(models.Model):
    created_by  = models.ForeignKey(User, on_delete=models.CASCADE )
    title = models.CharField(max_length=150,blank=True)
    keywords = models.CharField(max_length=150,blank=True)
    message = models.CharField(max_length=500,blank=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    purge = models.BooleanField(default=False)
    post_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
class Post(models.Model):
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE )
    content = models.CharField(max_length=500,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.forum.title

forums/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Forum, Post, User
# Create your views here.
share_forum_id = None

def index(request):
    print("*** in forums.index)")
    if request.user.is_authenticated:
        user_id = request.user.id
    else:
        return redirect('/')

    if request.method == 'POST':
        # prepare forum data
       
        if 'postmsg' in request.POST:
            postmsg = request.POST['postmsg']
            print("*** postmsg=", postmsg)

        else:
            print("*** no value")
        if postmsg:
            Forum.objects.create(
                created_by = request.user,
                message = postmsg,
            )

    forums = Forum.objects.order_by('-created_at')
    context = {
                'forums': forums,
    }
   # print("*** FORUM=", forums[1].message, " size=", forums.__sizeof__)
    return render(request, 'forums/index.html', context)
    
    
def forums(request, forum_id):
    if request.user.is_authenticated:
        user_id = request.user.id
    else:
        return redirect('/')
    global share_forum_id
    print("***in forums: id=", forum_id)
    forum = get_object_or_404(Forum, pk=forum_id)
    share_forum_id = forum_id
    post = Post.objects.order_by('-created_at').filter(forum_id=forum_id, posted_by_id=user_id)

    if post:
        context = {'forum':forum, 'post':post}
    else:
        context = {'forum':forum, 'post':{}}
    return render(request, 'forums/detail.html', context )


def search(request):
    queryset_list = Forum.objects.order_by('-created_at')
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(keywords__icontains=keywords)
            
    if 'title' in request.GET:
        title = request.GET['title']
        if title:
            queryset_list = queryset_list.filter(title__icontains=title)
            
    if 'message' in request.GET:
        message = request.GET['message']
        if message:
            queryset_list = queryset_list.filter(message__iexact=message)        


    context = {
        'forums': queryset_list,
        'total': len(queryset_list)
    }
    return render(request, 'forums/search.html', context)



def post(request):
    global share_forum_id
    print("### in forum:post ")
    # write record to Post
    context={}
    if request.user.is_authenticated:
        user_id = request.user.id
    else:
        return redirect('/')

    if request.method == 'POST':
        if 'postmsg' in request.POST:
            postmsg = request.POST['postmsg']
            print("*** postmsg=", postmsg)
        else:
            print("*** no value")
        if  share_forum_id:
            print("*** share_forum =", share_forum_id)

        obj_forum = Forum.objects.get(id=share_forum_id)
        obj_user = User.objects.get(id=user_id)
        post = Post(forum=obj_forum, posted_by=obj_user, content=postmsg)
        post.save()

        #update forum counter
        obj_forum.post_count += 1
        obj_forum.save()

#        if postmsg:
#            Post.objects.create(
#                forum = Forum,
#                posted_by = request.user,
#                content = postmsg,
#            )
#    post = Post.objects.order_by('-created_at')
#    context = {
#                'post': post,
#    }
#    return render(request, 'forums/detail.html', context)
    forum = get_object_or_404(Forum, pk=share_forum_id)
    post = Post.objects.order_by('-created_at').filter(forum_id=share_forum_id, posted_by_id=user_id)
    #post = get_object_or_404(Post, pk=forum_id)
    if post:
        context = {'forum':forum, 'post':post}
    else:
        context = {'forum':forum, 'post':{}}
    return render(request, 'forums/detail.html', context )

def add(request):
    context={}
    return render(request, 'forums/detail.html', context)

templates/forums/detail.html
{% extends 'base.html' %} 
{% load humanize %}

<!--add title to the tab-->
{% block title %} | Forum Details {% endblock %}
{% block content %}

{% include 'partials/_alert.html' %}
<!-- Forum -->
    <section id="Detail">
      <div class="w3-row">
      <div class="w3-rest w3-container text-left text-dark bg-white">
        {% if forum %}
          <div>
            <a class="fas text-dark"> {{forum.created_by}}</a>
            <i class="fas fa-clock">{{forum.created_at|timesince}} ago</i>
          </div>
            <li class="list-group-item bg-dark text-white">
            <a>
              {{ forum.message }}
            </a>
            </li>
            {% if forum.photo_main %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_main.url}}></div>
            </div>
            {% endif %}
            {% if forum.photo_1 %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_1.url}}></div>
            </div>
            {% endif %}
            {% if forum.photo_2 %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_2.url}}></div>
            </div>
            {% endif %}
            
            <div>
              <i class="fas fa-comment fa-sm mr-1"></i>
              <a># of posts: {{forum.post_count}}</a>
            </div>
            
        {% else %}
            <a>no Forum found</a>
        {% endif %}
        <hr>
      </div>
      </div>
    </section>

<!-- post box -->
    <form action="{% url 'forums:post' %}" method="post">
      {% csrf_token %}
      <div>
      <textarea id="expandingTextarea" name="postmsg" placeholder="{{user.username}}, Post your reply"></textarea>
    
        <script>
            // JavaScript to make the textarea expand as you type
            const textarea = document.getElementById('expandingTextarea');
    
            textarea.addEventListener('input', function() {
                // Reset the height to auto to shrink back to the default size if needed
                this.style.height = 'auto';
    
                // Set the height to the scroll height to expand to fit the content
                this.style.height = this.scrollHeight + 'px';
            });
        </script>
      </div>
    <div>
        <button type="submit">Post</button>
    </div>
    </form>
    <hr>

<!-- other Posts -->
<section id="Post">
  <div class="w3-row">
  <div class="w3-rest w3-container text-left text-dark bg-white">
    {% if post %}
              {% for p in post %}
              <br>
              <div>
                <a> {{p.posted_by}}</a>
                <i class="fas fa-clock">{{p.created_at|timesince}} ago</i>
              </div>
              {{p.content}}
              {% endfor %}
            {% else %}
              <a> no new post</a>
            {% endif %}
    <hr>
  </div>
  </div>
</section>
<!--
    <section id="services" class="py-5 bg-secondary text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-4">
            <i class="fas fa-comment fa-4x mr-4"></i>
            <hr />
            <h3>Consulting Services</h3>
            <p>
              Our management consulting services focus on our clients'
               most critical issues and opportunities: strategy, 
               marketing, organization, operations, technology, 
               transformation, digital, advanced analytics, corporate
                finance, and sustainability
                 across all industries and geographies. 
            </p>
          </div>
          <div class="col-md-4">
            <i class="fas fa-home fa-4x mr-4"></i>
            <hr />
            <h3>Academy</h3>
            <p>
              Unlimited access to 27,000+ fresh courses across tech, business, leadership, and wellness
Robust platform features offering on-demand, immersive, and cohort-based learning for your team
Personalized learning and actionable learner insights to drive high usage and course completion rates
            </p>
          </div>
          <div class="col-md-4">
            <i class="fas fa-suitcase fa-4x mr-4"></i>
            <hr />
            <h3>Infrastructure</h3>
            <p>
              You’re probably already aware of the potential of cloud 
              computing to transform your organization. As you explore
               moving away from self-managed on-premises IT solutions,
                it’s important to understand the different options available to you when it comes to cloud computing services.  
            </p>
          </div>
        </div>
      </div>
    </section> 
  -->
{% endblock %}

templates/forums/index.html
{% extends 'base.html' %} 
{% load humanize %}

<!--add title to the tab-->
{% block title %} | Forum {% endblock %}
{% block content %}

{% include 'partials/_alert.html' %}
<form action="{% url 'forums:index' %}" method="post">
  {% csrf_token %}
  <div>
      <label for="postmsg">Post Content:</label><br>
<textarea id="postmsg" name="postmsg" placeholder="{{user.username}}, what is Happening ..."></textarea>

    <script>
        // JavaScript to make the textarea expand as you type
        const textarea = document.getElementById('postmsg');

        textarea.addEventListener('input', function() {
            // Reset the height to auto to shrink back to the default size if needed
            this.style.height = 'auto';

            // Set the height to the scroll height to expand to fit the content
            this.style.height = this.scrollHeight + 'px';
        });
    </script>
</div>
<div>
    <button type="submit">Post</button><i class="fa fa-file-image-o"></i>
</div>
</form>
    <hr>

<!-- Forum -->
    <section id="Forums">
      <div class="w3-rest w3-container text-left text-dark bg-white">
        {% if forums %}
        {% for forum in forums %}
            <div>
              <a> {{forum.created_by}}</a>
              <i class="fas fa-clock">{{forum.created_at|timesince}} ago</i>
            </div>
            <li class="list-group-item">
            <a href="{% url 'forums:forums' forum.id %}">
              {{ forum.message }}
            </a>
            </li>
            {% if forum.photo_main %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_main.url}}></div>
            </div>
            {% endif %}
            {% if forum.photo_1 %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_1.url}}></div>
            </div>
            {% endif %}
            {% if forum.photo_2 %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_2.url}}></div>
            </div>
            {% endif %}
            <div>
              <i class="fas fa-comment fa-sm mr-1"></i>
              <a># of posts: {{forum.post_count}}</a>
            </div>
            <hr>
        {% endfor %}
        {% else %}
            <a>no Forum found</a>
        {% endif %}
        <hr class="text-white bg-dark">
      </div>
    </section>
<!--
    <section id="services" class="py-5 bg-secondary text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-4">
            <i class="fas fa-comment fa-4x mr-4"></i>
            <hr />
            <h3>Consulting Services</h3>
            <p>
              Our management consulting services focus on our clients'
               most critical issues and opportunities: strategy, 
               marketing, organization, operations, technology, 
               transformation, digital, advanced analytics, corporate
                finance, and sustainability
                 across all industries and geographies. 
            </p>
          </div>
          <div class="col-md-4">
            <i class="fas fa-home fa-4x mr-4"></i>
            <hr />
            <h3>Academy</h3>
            <p>
              Unlimited access to 27,000+ fresh courses across tech, business, leadership, and wellness
Robust platform features offering on-demand, immersive, and cohort-based learning for your team
Personalized learning and actionable learner insights to drive high usage and course completion rates
            </p>
          </div>
          <div class="col-md-4">
            <i class="fas fa-suitcase fa-4x mr-4"></i>
            <hr />
            <h3>Infrastructure</h3>
            <p>
              You’re probably already aware of the potential of cloud 
              computing to transform your organization. As you explore
               moving away from self-managed on-premises IT solutions,
                it’s important to understand the different options available to you when it comes to cloud computing services.  
            </p>
          </div>
        </div>
      </div>
    </section>
  -->
{% endblock %}

templates/forums/posting.html
{% extends 'base.html' %} 
{% load humanize %}
<!--add title to the tab-->
{% block title %} | Forum {% endblock %}
{% block content %}

{% include 'partials/_alert.html' %}

<!-- Forum Posting-->
    <section id="Postings">
      <div class="w3-row">
      <div class="w3-rest w3-container text-left" style="height:300px;">
        {% if forum %}
            <div class="inline-block"><p>{{ forum.create_by }}</p></div>
            <div class="inline-block fas fa-clock"><p>{{forum.created_at|timesince}}</p></div>
            <li class="list-group-item">
            <a href="{% url 'forums' forums.id %}">
              {{ forum.message }}
            </a>
            </li>
            {% if forum.photo_main %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_main.url}}></div>
            </div>
            {% endif %}
            {% if forum.photo_1 %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_1.url}}></div>
            </div>
            {% endif %}
            {% if forum.photo_2 %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_2.url}}></div>
            </div>
            {% endif %}
            <hr>
            <div>
              <a># posts: {{forum.post_count}}</a>
            </div>
        {% else %}
            <p>no Forum found</p>
        {% endif %}
        <!-- posts -->
        {% if post %}
          {% for item in post}
        {% end for %}
        {% else %}
          <p>no post</p>
        {% endif %}
        <hr>
      </div>
      </div>
    </section>

{% endblock %}

templates/forums/search.html
{% extends 'base.html' %} 
{% load humanize %}
<!--add title to the tab-->
{% block title %} | Forum {% endblock %}
{% block content %}

{% include 'partials/_alert.html' %}

<!-- Forum -->
    <section id="Forums">
      <form action="{% url 'forums:add' %}" method="POST">
        <label for="content">What is happening?</label><br>
        <textarea id="newpost" name="newpost" rows="1" maxlength="300"></textarea>
      </form>
      <div class="w3-row">
      <div class="w3-rest w3-container text-left" style="height:300px;">
        {% if forums %}
        {% for forum in forums %}
            <div class="inline-block"><p>{{ forum.create_by }}</p></div>
            <div class="inline-block fas fa-clock"><p>{{forum.created_at|timesince}}</p></div>
            <li class="list-group-item">
            <a href="{% url 'forums' forums.id %}">
              {{ forum.message }}
            </a>
            </li>
            {% if forum.photo_main %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_main.url}}></div>
            </div>
            {% endif %}
            {% if forum.photo_1 %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_1.url}}></div>
            </div>
            {% endif %}
            {% if forum.photo_2 %}
            <div class="w3-row">
              <div class="w3-col s4"><img src={{forum.photo_2.url}}></div>
            </div>
            {% endif %}
            <hr>
            <div>
              <a># posts: {{forum.post_count}}</a>
            </div>
        {% endfor %}
        {% else %}
            <p>no Forum found</p>
        {% endif %}
        <hr>
      </div>
      </div>
    </section>

    <section id="services" class="py-5 bg-secondary text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-4">
            <i class="fas fa-comment fa-4x mr-4"></i>
            <hr />
            <h3>Consulting Services</h3>
            <p>
              dignissimos ratione ea quae.
            </p>
          </div>
          <div class="col-md-4">
            <i class="fas fa-home fa-4x mr-4"></i>
            <hr />
            <h3>Propery Management</h3>
            <p>
              dignissimos ratione ea quae.
            </p>
          </div>
          <div class="col-md-4">
            <i class="fas fa-suitcase fa-4x mr-4"></i>
            <hr />
            <h3>Renting & Selling</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt,
              debitis nam! Repudiandae, provident iste consequatur hic
              dignissimos ratione ea quae.
            </p>
          </div>
        </div>
      </div>
    </section>
{% endblock %}